name: iOSProjectTemplate
options:
  minimumXcodeGenVersion: 2.16.0
  groupSortPosition: top
  generateEmptyDirectories: true
  bundleIdPrefix: com.mothule
  postGenCommand: pod install

configs:
  Debug: debug
  CI: debug
  Release: release

targets:
  App:
    type: application
    platform: iOS
    sources: App
    dependencies:
      - target: Core
    postbuildScripts:
      - name: Run SwiftLint
        script: |
                if [[ -f ./Mintfile ]] ; then
                  mint run swiftlint
                else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi

  AppTests:
    type: bundle.unit-test
    platform: iOS
    sources: AppTests
    dependencies:
      - target: App
      - carthage: Quick
      - carthage: Nimble
  Core:
    type: framework
    platform: iOS
    sources: Core
  CoreTests:
    type: bundle.unit-test
    platform: iOS
    sources: CoreTests
    dependencies:
      - target: Core
      - carthage: Quick
      - carthage: Nimble

schemes:
  iOSProjectTemplate:
    build:
      targets:
        App: all
        AppTests: [test]
    test:
      targets:
        - AppTests
        - CoreTests
      config: CI
      gatherCoverageData: true

        
