name: iOSProjectTemplate
options:
  bundleIdPrefix: com.mothule

configs:
  Debug: debug
  CI: debug
  Beta: release
  AppStore: release

targets:
  iOSProjectTemplate:
    type: application
    platform: iOS
    sources: ios_project_template
  iOSProjectTemplateTests:
    type: bundle.unit-test
    platform: iOS
    sources: ios_project_templateTests
    dependencies:
      - target: iOSProjectTemplate
      - carthage: Quick
      - carthage: Nimble
