name: iOSProjectTemplate
options:
  minimumXcodeGenVersion: 2.16.0
  groupSortPosition: top
  generateEmptyDirectories: true
  bundleIdPrefix: com.mothule
  postGenCommand: pod install

configs:
  Debug: debug
  CI: debug
  Release: release

targets:
  iOSProjectTemplate:
    type: application
    platform: iOS
    sources: ios_project_template
    dependencies:
      - target: Core
  iOSProjectTemplateTests:
    type: bundle.unit-test
    platform: iOS
    sources: ios_project_templateTests
    dependencies:
      - target: iOSProjectTemplate
      - carthage: Quick
      - carthage: Nimble
  Core:
    type: framework
    platform: iOS
    sources: Core
  CoreTests:
    type: bundle.unit-test
    platform: iOS
    sources: CoreTests
    dependencies:
      - target: Core
      - carthage: Quick
      - carthage: Nimble

schemes:
  iOSProjectTemplate:
    build:
      targets:
        iOSProjectTemplate: all
        iOSProjectTemplateTests: [test]
    test:
      targets:
        - iOSProjectTemplateTests
      config: CI
      gatherCoverageData: true

        
