name: iOSProjectTemplate
options:
  bundleIdPrefix: com.mothule
  postGenCommand: pod install

configs:
  Debug: debug
  CI: debug
  Beta: release
  AppStore: release

targets:
  iOSProjectTemplate:
    type: application
    platform: iOS
    sources: ios_project_template
  iOSProjectTemplateTests:
    type: bundle.unit-test
    platform: iOS
    sources: ios_project_templateTests
    dependencies:
      - target: iOSProjectTemplate
      - carthage: Quick
      - carthage: Nimble

schemes:
  iOSProjectTemplate:
    build:
      targets:
        iOSProjectTemplate: all
        iOSProjectTemplateTests: [test]
    test:
      targets:
        - iOSProjectTemplateTests
      config: CI
      gatherCoverageData: true

        
